### ISSUE TITLE
Couldn't load packages due to errors

### ISSUE THREAD

**Issue by ndbeals** [redefiance/atom-go-rename#6]
As the title says, When i try to use go-rename atom gives me that error as a red pop up, and yes i do have gorename installed. I even tried setting the path setting directly to it and it still doesn't work.

**Comment by dvdplm** [comment]
Same issue here. :/

```
$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dvd/dev/go/gocode"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.4.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

```
$ which gorename
/Users/dvd/dev/go/gocode/bin/gorename
```

**Comment by EZ-BZ** [comment]
Had the same problem.
Mine has caused by the go1.5 vendor feature (third party packages sits under my project workspace).
To identify that's the real root cause run some gorename command on terminal and see if you still get the same error 
go rename command should look something like: 
```gorename -from '"github.com/[my_repo]/[some_project]/[some_pkg]".[old_func]' -to [new_func]```

The workaround is quite a hack but works for me:
* Add your project's ```vendor``` directory to your ```GOPATH```  . For example,
lets say my GOPATH is ```$HOME/go```, and my project code reside at  ```$HOME/go/src/github.com/my_repo/my_project```
then my ```GOPATH``` should look something like this:
*```GOPATH=$HOME/go:$HOME/go/src/github.com/my_repo/my_project/vendor```*
* Next create symlink called 'src' under vendor directory which links to itself. For example:  under vendor dir run ```ln -s . src```

Thank you @gavrie

**Comment by luck02** [comment]
no dice here, so gorename doesn't work with vendored dependencies.
That really kind of sucks :(
